### ISSUE TITLE
Rename to FluentTimeSpan & transfer to conplement

### ISSUE THREAD

**Issue by GuepardoApps** [conplementAG/FluentTimeSpan#3]

**Comment by GuepardoApps** [comment]
Renamed to FluentTimeSpan with this [Commit](https://github.com/TimeXt/FluentTimeSpan-CSharp/commit/7a27cf76cf1aab014319ea4719969a7fecc30675)

**Comment by DenisBiondic** [comment]
Invite should be in your inbox, try to do it with "transfer ownership". If it does not work, we could simple git remote add & push.

Suggestion: Let's drop the -CSharp from the name. FluentTimeSpan is cleaner, and via tagging / description it will be written that it is about C# ;)

**Comment by GuepardoApps** [comment]
I don’t have the permission to create repositories on conplementAG yet. Do you have to unlock that?

**Comment by GuepardoApps** [comment]
-CSharp was added when I implemented this features for different languages (JS, Kotlin, etc.). Will drop it ;)

**Comment by DenisBiondic** [comment]
@GuepardoApps You don't need the permission, you should go to repository settings and do:

![image](https://user-images.githubusercontent.com/3341262/47869701-ebfa8000-de07-11e8-8fed-d56421881785.png)

That way, the issue and git history will also be migrated.

**Comment by DenisBiondic** [comment]
Oh, wait, perhaps I wrote that too fast, it even says there that "you have to have the ability to create repositories" :)

**Comment by DenisBiondic** [comment]
OK, transfer should work now for you too, I granted more rights

**Comment by GuepardoApps** [comment]
Would be nice if I get more rights to update here ;)

**Comment by DenisBiondic** [comment]
Of course, you’re the admin on the repository now.
